FROM openjdk:11 as build
WORKDIR /workspace/app

COPY mvnw .
COPY .mvn .mvn
COPY pom.xml .
COPY src src

RUN ./mvnw install -DskipTests
ENTRYPOINT ["java", "-jar", "./target/task-0.0.1-SNAPSHOT.jar"]



#docker build -f DockerFile -t task .
#docker container run -p 8080:8080 task